Repository Pyomo/pyomo, pull requests merged in 2018-12, with the labels that each got.

#780 Fixing doctests for Pyomo.Network
  .readthedocs_requirements.txt
  .travis.yml
Labels: IDAES related

#678 Allow user, password and database to be passed as options for pymysql
  pyomo/dataportal/plugins/db_table.py
  pyomo/dataportal/process_data.py
Labels: AT: STALE

#738 Trustregion cfgblk
  pyomo/contrib/trustregion/GeometryGenerator.py
  pyomo/contrib/trustregion/Logger.py
  pyomo/contrib/trustregion/PyomoInterface.py
  pyomo/contrib/trustregion/TRF.py
  pyomo/contrib/trustregion/filterMethod.py
  pyomo/contrib/trustregion/param.py
  pyomo/contrib/trustregion/plugins.py
  pyomo/contrib/trustregion/tests/TestTRConfig.py
Labels: documentation

#717 GLOA implementation and GDPopt updates
  examples/gdp/small_lit/README.md
  examples/gdp/small_lit/ex_633_trespalacios.py
  pyomo/contrib/gdpopt/GDPopt.py
  pyomo/contrib/gdpopt/cut_generation.py
  pyomo/contrib/gdpopt/iterate.py
  pyomo/contrib/gdpopt/master_initialize.py
  pyomo/contrib/gdpopt/mip_solve.py
  pyomo/contrib/gdpopt/nlp_solve.py
  pyomo/contrib/gdpopt/tests/test_gdpopt.py
  pyomo/contrib/gdpopt/util.py
  pyomo/contrib/mcpp/.gitignore
  pyomo/contrib/mcpp/__init__.py
  pyomo/contrib/mcpp/mcppInterface.cpp
  pyomo/contrib/mcpp/pyomo_mcpp.py
  pyomo/contrib/mcpp/test_mccpp.py
Labels: AT: STALE
