Repository Pyomo/pyomo, pull requests merged in 2018-05, with the labels that each got.

#462 Doctest fix
  .travis.yml
Labels: testing_and_ci

#463 Preemptive Python-3.7 fixes in PySP
  examples/pysp/scripting/apps/compile_scenario_tree.py
  pyomo/pysp/embeddedsp.py
  pyomo/pysp/ph.py
  pyomo/pysp/phinit.py
  pyomo/pysp/plugins/ecksteincombettesextension.py
  pyomo/pysp/scenariotree/manager.py
  pyomo/pysp/scenariotree/manager_solver.py
  pyomo/pysp/scenariotree/manager_worker_pyro.py
  pyomo/pysp/solvers/admm.py
  pyomo/pysp/solvers/benders.py
  pyomo/pysp/solvers/ddsip.py
  pyomo/pysp/tests/scenariotreemanager/test_scenariotreemanager.py
  pyomo/pysp/tests/scenariotreemanager/test_scenariotreemanagersolver.py
Labels: pyomo.pysp

#485 Add quotes around paths in cplex script file
  CHANGELOG.txt
  pyomo/solvers/plugins/solvers/CPLEX.py
Labels: pyomo.solvers

#481 Disjunctive bounds
  pyomo/contrib/gdp_bounds/__init__.py
  pyomo/contrib/gdp_bounds/plugins/__init__.py
  pyomo/contrib/gdp_bounds/plugins/compute_bounds.py
  pyomo/contrib/gdp_bounds/tests/__init__.py
  pyomo/contrib/gdp_bounds/tests/test_gdp_bounds.py
  pyomo/environ/__init__.py
Labels: IDAES related

#487 Allow targets to be specified for fix_disjuncts transformation
  pyomo/gdp/plugins/fix_disjuncts.py
  pyomo/gdp/tests/test_fix_disjuncts.py
Labels: IDAES related

#498 Remove GDP var mover false positive warning
  pyomo/gdp/plugins/gdp_var_mover.py
  pyomo/gdp/tests/models.py
  pyomo/gdp/tests/test_bigm.py
  pyomo/gdp/tests/test_reclassify.py
Labels: IDAES related

#522 Move kernel util
  pyomo/core/kernel/__init__.py
  pyomo/core/tests/unit/test_component_block.py
  pyomo/core/tests/unit/test_component_constraint.py
  pyomo/core/tests/unit/test_component_dict.py
  pyomo/core/tests/unit/test_component_expression.py
  pyomo/core/tests/unit/test_component_matrix_constraint.py
  pyomo/core/tests/unit/test_component_objective.py
  pyomo/core/tests/unit/test_component_parameter.py
  pyomo/core/tests/unit/test_component_sos.py
  pyomo/core/tests/unit/test_component_suffix.py
  pyomo/core/tests/unit/test_component_variable.py
  pyomo/kernel/__init__.py
  pyomo/kernel/util.py
Labels: pyomo.core
