Repository Pyomo/pyomo, pull requests merged in 2018-06, with the labels that each got.

#546 Only test master (and PRs)
  .appveyor.yml
  .travis.yml
Labels: testing_and_ci

#549 Move integer tolerance to ConfigBlock for fix_disjuncts
  pyomo/gdp/plugins/fix_disjuncts.py
Labels: IDAES related

#544 Casadi integrator fix
  pyomo/dae/simulator.py
  pyomo/dae/tests/test_simulator.py
Labels: IDAES related

#536 Update the trustregion package for Pyomo5 expressions
  pyomo/contrib/trustregion/PyomoInterface.py
  pyomo/core/expr/expr_pyomo5.py
  pyomo/core/tests/unit/test_expr_pyomo5.py
Labels: IDAES related

#569 Kernel Update 1: Simplify handling of active status on containers
  pyomo/core/kernel/component_block.py
  pyomo/core/kernel/component_constraint.py
  pyomo/core/kernel/component_interface.py
  pyomo/core/kernel/component_matrix_constraint.py
  pyomo/core/kernel/component_objective.py
  pyomo/core/kernel/component_sos.py
  pyomo/core/kernel/component_suffix.py
  pyomo/core/tests/unit/test_component_block.py
  pyomo/core/tests/unit/test_component_constraint.py
  pyomo/core/tests/unit/test_component_dict.py
  pyomo/core/tests/unit/test_component_expression.py
  pyomo/core/tests/unit/test_component_list.py
  pyomo/core/tests/unit/test_component_matrix_constraint.py
  pyomo/core/tests/unit/test_component_objective.py
  pyomo/core/tests/unit/test_component_piecewise.py
  pyomo/core/tests/unit/test_component_sos.py
  pyomo/core/tests/unit/test_component_suffix.py
  pyomo/core/tests/unit/test_component_tuple.py
  pyomo/core/tests/unit/test_component_variable.py
  pyomo/kernel/util.py
  pyomo/solvers/tests/models/LP_inactive_index.py
  pyomo/solvers/tests/models/LP_unused_vars.py
  pyomo/solvers/tests/models/MILP_unused_vars.py
Labels: pyomo.core

#533 Forward-pass implementation of variable aggregation
  pyomo/contrib/preprocessing/plugins/__init__.py
  pyomo/contrib/preprocessing/plugins/var_aggregator.py
  pyomo/contrib/preprocessing/tests/test_var_aggregator.py
Labels: IDAES related

#581 Add a GDP example problem from literature
  examples/gdp/two_rxn_lee/README.md
  examples/gdp/two_rxn_lee/two_rxn_model.py
Labels: IDAES related

#579 Model size report utility
  pyomo/util/model_size.py
  pyomo/util/tests/test_model_size.py
Labels: IDAES related

#582 Improper basic steps implementation
  pyomo/gdp/basic_step.py
  pyomo/gdp/tests/test_basic_step.py
Labels: IDAES related

#589 fixing _linear_canonical_form flag on linear_constraint
  pyomo/core/kernel/component_constraint.py
  pyomo/core/tests/unit/test_component_constraint.py
  pyomo/core/tests/unit/test_component_matrix_constraint.py
Labels: pyomo.core

#590 Fix to solver tempfiles
  pyomo/contrib/trustregion/PyomoInterface.py
  pyomo/contrib/trustregion/plugins.py
  pyomo/contrib/trustregion/readgjh.py
  pyomo/solvers/plugins/converter/model.py
  pyomo/solvers/plugins/solvers/GUROBI.py
Labels: pyomo.solvers
