Repository Pyomo/pyomo, pull requests merged in 2018-10, with the labels that each got.

#701 BARON.py missing pyutilib import
  pyomo/solvers/plugins/solvers/BARON.py
Labels: pyomo.solvers

#675 Cython2
  pyomo/core/expr/expr_pyomo5.c
  pyomo/core/expr/numvalue.c
  pyomo/core/util.c
  pyomo/repn/standard_repn.c
  setup.py
Labels: enhancement

#698 Fix double-operator due to negative constant in GAMS Writer
  pyomo/repn/plugins/gams_writer.py
  pyomo/repn/tests/gams/small13.pyomo.gms
  pyomo/repn/tests/gams/small5.pyomo.gms
  pyomo/repn/tests/gams/small6.pyomo.gms
  pyomo/repn/tests/gams/small7.pyomo.gms
  pyomo/repn/tests/gams/small8.pyomo.gms
  pyomo/repn/tests/gams/test_gams.py
  pyomo/repn/tests/test_gams.py
Labels: IDAES related

#706 Contrib parmest
  doc/OnlineDocs/contributed_packages/index.rst
  doc/OnlineDocs/contributed_packages/parmest/api.rst
  doc/OnlineDocs/contributed_packages/parmest/bibliography.rst
  doc/OnlineDocs/contributed_packages/parmest/callback.rst
  doc/OnlineDocs/contributed_packages/parmest/driver.rst
  doc/OnlineDocs/contributed_packages/parmest/examples.rst
  doc/OnlineDocs/contributed_packages/parmest/index.rst
  doc/OnlineDocs/contributed_packages/parmest/installation.rst
  doc/OnlineDocs/contributed_packages/parmest/overview.rst
  doc/OnlineDocs/contributed_packages/parmest/parallel.rst
  doc/OnlineDocs/index.rst
  pyomo/contrib/parmest/__init__.py
  pyomo/contrib/parmest/examples/__init__.py
  pyomo/contrib/parmest/examples/mea/__init__.py
  pyomo/contrib/parmest/examples/mea/mea_drive_parmest.py
  pyomo/contrib/parmest/examples/rooney_biegler/__init__.py
  pyomo/contrib/parmest/examples/rooney_biegler/all_in_one.py
  pyomo/contrib/parmest/examples/rooney_biegler/rb_drive_parmest.py
  pyomo/contrib/parmest/examples/rooney_biegler/rooney_biegler.py
  pyomo/contrib/parmest/examples/semibatch/__init__.py
  pyomo/contrib/parmest/examples/semibatch/exp1.out
  pyomo/contrib/parmest/examples/semibatch/exp10.out
  pyomo/contrib/parmest/examples/semibatch/exp11.out
  pyomo/contrib/parmest/examples/semibatch/exp12.out
  pyomo/contrib/parmest/examples/semibatch/exp13.out
  pyomo/contrib/parmest/examples/semibatch/exp14.out
  pyomo/contrib/parmest/examples/semibatch/exp2.out
  pyomo/contrib/parmest/examples/semibatch/exp3.out
  pyomo/contrib/parmest/examples/semibatch/exp4.out
  pyomo/contrib/parmest/examples/semibatch/exp5.out
  pyomo/contrib/parmest/examples/semibatch/exp6.out
  pyomo/contrib/parmest/examples/semibatch/exp7.out
  pyomo/contrib/parmest/examples/semibatch/exp8.out
  pyomo/contrib/parmest/examples/semibatch/exp9.out
  pyomo/contrib/parmest/examples/semibatch/sb_drive_parmest.py
  pyomo/contrib/parmest/examples/semibatch/semibatch.py
  pyomo/contrib/parmest/graphics.py
  pyomo/contrib/parmest/ipopt_solver_wrapper.py
  pyomo/contrib/parmest/mpi_utils.py
  pyomo/contrib/parmest/parmest.py
  pyomo/contrib/parmest/tests/__init__.py
  pyomo/contrib/parmest/tests/test_parmest.py
Labels: IDAES related
