Repository Pyomo/pyomo, pull requests merged in 2018-02, with the labels that each got.

#337 GDPopt solver initial implementation
  pyomo/contrib/gdpopt/GDPopt.py
  pyomo/contrib/gdpopt/__init__.py
  pyomo/contrib/gdpopt/tests/__init__.py
  pyomo/contrib/gdpopt/tests/eight_process_problem.py
  pyomo/contrib/gdpopt/tests/test_gdpopt.py
  pyomo/core/base/symbolic.py
  pyomo/core/plugins/transform/__init__.py
  pyomo/environ/__init__.py
  pyomo/gdp/tests/test_chull.py
Labels: IDAES related

#363 Fix to gurobi_direct initialization when gurobipy is not available.
  pyomo/solvers/plugins/solvers/gurobi_direct.py
Labels: bug

#368 Misc Gurobi and Cplex fixes
  pyomo/solvers/plugins/solvers/GUROBI_RUN.py
  pyomo/solvers/plugins/solvers/cplex_direct.py
  pyomo/solvers/plugins/solvers/gurobi_direct.py
Labels: bug

#366 Remove checks for is_indexed from PersistentSolver methods
  pyomo/solvers/plugins/solvers/cplex_persistent.py
  pyomo/solvers/plugins/solvers/gurobi_persistent.py
  pyomo/solvers/plugins/solvers/persistent_solver.py
Labels: enhancement

#374 Handle USER_OBJ_LIMIT solver status in Gurobi Python and LP solver interfaces.
  pyomo/solvers/plugins/solvers/GUROBI_RUN.py
  pyomo/solvers/plugins/solvers/gurobi_direct.py
Labels: pyomo.solvers
