Repository Pyomo/pyomo, pull requests merged in 2019-01, with the labels that each got.

#793 Neos fixes
  pyomo/neos/kestrel.py
  pyomo/neos/plugins/NEOS.py
  pyomo/neos/plugins/kestrel_plugin.py
  pyomo/neos/tests/test_neos.py
Labels: AT: STALE

#801 Example 633 Trespalacios Comment Fix
  examples/gdp/small_lit/ex_633_trespalacios.py
Labels: AT: PRE-TEST INSPECTED

#803 Allow Handling for RangeSet in BigM and cHull transformations
  pyomo/gdp/plugins/bigm.py
  pyomo/gdp/plugins/chull.py
  pyomo/gdp/tests/models.py
  pyomo/gdp/tests/test_bigm.py
  pyomo/gdp/tests/test_chull.py
Labels: IDAES related, pyomo.gdp

#814 Updated parmest API
  doc/OnlineDocs/bibliography.rst
  doc/OnlineDocs/contributed_packages/parmest/RB.png
  doc/OnlineDocs/contributed_packages/parmest/RB_LR.png
  doc/OnlineDocs/contributed_packages/parmest/RB_boot.png
  doc/OnlineDocs/contributed_packages/parmest/api.rst
  doc/OnlineDocs/contributed_packages/parmest/bibliography.rst
  doc/OnlineDocs/contributed_packages/parmest/callback.rst
  doc/OnlineDocs/contributed_packages/parmest/driver.rst
  doc/OnlineDocs/contributed_packages/parmest/examples.rst
  doc/OnlineDocs/contributed_packages/parmest/graphics.rst
  doc/OnlineDocs/contributed_packages/parmest/index.rst
  doc/OnlineDocs/contributed_packages/parmest/installation.rst
  doc/OnlineDocs/contributed_packages/parmest/overview.rst
  doc/OnlineDocs/contributed_packages/parmest/pairwise_plot_CI.png
  doc/OnlineDocs/contributed_packages/parmest/pairwise_plot_LR.png
  doc/OnlineDocs/contributed_packages/parmest/parallel.rst
  pyomo/contrib/parmest/examples/mea/mea_drive_parmest.py
  pyomo/contrib/parmest/examples/reactor_design/__init__.py
  pyomo/contrib/parmest/examples/reactor_design/reactor_data.xlsx
  pyomo/contrib/parmest/examples/reactor_design/reactor_data_multisensor.xlsx
  pyomo/contrib/parmest/examples/reactor_design/reactor_data_timeseries.xlsx
  pyomo/contrib/parmest/examples/reactor_design/reactor_design.py
  pyomo/contrib/parmest/examples/reactor_design/reactor_design_parmest.py
  pyomo/contrib/parmest/examples/reactor_design/reactor_design_parmest_multisensor.py
  pyomo/contrib/parmest/examples/reactor_design/reactor_design_parmest_timeseries.py
  pyomo/contrib/parmest/examples/rooney_biegler/all_in_one.py
  pyomo/contrib/parmest/examples/rooney_biegler/rb_drive_parmest.py
  pyomo/contrib/parmest/examples/rooney_biegler/rooney_biegler.py
  pyomo/contrib/parmest/examples/rooney_biegler/rooney_biegler_parmest.py
  pyomo/contrib/parmest/examples/semibatch/exp1.out
  pyomo/contrib/parmest/examples/semibatch/exp10.out
  pyomo/contrib/parmest/examples/semibatch/exp11.out
  pyomo/contrib/parmest/examples/semibatch/exp12.out
  pyomo/contrib/parmest/examples/semibatch/exp13.out
  pyomo/contrib/parmest/examples/semibatch/exp14.out
  pyomo/contrib/parmest/examples/semibatch/exp2.out
  pyomo/contrib/parmest/examples/semibatch/exp3.out
  pyomo/contrib/parmest/examples/semibatch/exp4.out
  pyomo/contrib/parmest/examples/semibatch/exp5.out
  pyomo/contrib/parmest/examples/semibatch/exp6.out
  pyomo/contrib/parmest/examples/semibatch/exp7.out
  pyomo/contrib/parmest/examples/semibatch/exp8.out
  pyomo/contrib/parmest/examples/semibatch/exp9.out
  pyomo/contrib/parmest/examples/semibatch/sb_drive_parmest.py
  pyomo/contrib/parmest/examples/semibatch/semibatch.py
  pyomo/contrib/parmest/examples/semibatch/semibatch_parmest.py
  pyomo/contrib/parmest/examples/semibatch/semibatch_parmest_parallel.py
  pyomo/contrib/parmest/graphics.py
  pyomo/contrib/parmest/parmest.py
  pyomo/contrib/parmest/tests/test_parmest.py
Labels: AT: PRE-TEST INSPECTED, IDAES related

#805 GDPopt update
  pyomo/contrib/gdpopt/GDPopt.py
  pyomo/contrib/gdpopt/cut_generation.py
  pyomo/contrib/gdpopt/data_class.py
  pyomo/contrib/gdpopt/iterate.py
  pyomo/contrib/gdpopt/master_initialize.py
  pyomo/contrib/gdpopt/mip_solve.py
  pyomo/contrib/gdpopt/nlp_solve.py
  pyomo/contrib/gdpopt/tests/test_gdpopt.py
  pyomo/contrib/gdpopt/util.py
  pyomo/contrib/preprocessing/plugins/__init__.py
  pyomo/contrib/preprocessing/plugins/int_to_binary.py
  pyomo/contrib/preprocessing/tests/test_int_to_binary.py
Labels: IDAES related

#667 Bugfix for GDP var mover
  pyomo/gdp/plugins/gdp_var_mover.py
  pyomo/gdp/tests/test_reclassify.py
Labels: IDAES related

#830 Improvements to Reference for supporting sparse components
  pyomo/core/base/indexed_component_slice.py
  pyomo/core/base/reference.py
  pyomo/core/tests/unit/test_reference.py
Labels: IDAES related
