Repository Pyomo/pyomo, pull requests merged in 2019-06, with the labels that each got.

#1045 Remove non-ascii character from README.md
  README.md
Labels: pyomo.installation

#955 Model viewer install/testing
  pyomo/contrib/viewer/README.md
  pyomo/contrib/viewer/main.ui
  pyomo/contrib/viewer/model_browser.py
  pyomo/contrib/viewer/pyomo_viewer.py
  pyomo/contrib/viewer/pyqt_4or5.py
  pyomo/contrib/viewer/tests/pytest_qt.py
  pyomo/contrib/viewer/tests/test_qt.py
  pyomo/contrib/viewer/ui.py
  setup.py
Labels: AT: STALE

#1060 Avoid cplex_direct "No Solution Exists" Messages
  pyomo/solvers/plugins/solvers/cplex_direct.py
Labels: pyomo.solvers

#1063 Tweaking the collection of standard_repn
  pyomo/repn/standard_repn.py
Labels: performance
