Repository Pyomo/pyomo, pull requests merged in 2019-08, with the labels that each got.

#1094 Update working_models.rst
  doc/OnlineDocs/working_models.rst
Labels: AT: PRE-TEST INSPECTED

#989 Replace ReciprocalExpression with DivisionExpression
  pyomo/contrib/fbbt/fbbt.py
  pyomo/contrib/mcpp/mcppInterface.cpp
  pyomo/contrib/mcpp/pyomo_mcpp.py
  pyomo/contrib/satsolver/satsolver.py
  pyomo/core/base/units_container.py
  pyomo/core/expr/calculus/diff_with_pyomo.py
  pyomo/core/expr/numeric_expr.py
  pyomo/core/tests/unit/test_numeric_expr.py
  pyomo/core/tests/unit/test_symbolic.py
  pyomo/core/tests/unit/test_units.py
  pyomo/core/tests/unit/test_util.py
  pyomo/core/tests/unit/test_visitor.py
  pyomo/dae/simulator.py
  pyomo/dae/tests/test_simulator.py
  pyomo/gdp/tests/test_chull.py
  pyomo/repn/plugins/ampl/ampl_.py
  pyomo/repn/plugins/baron_writer.py
  pyomo/repn/plugins/gams_writer.py
  pyomo/repn/standard_repn.py
  pyomo/repn/tests/ampl/small14.pyomo.nl
  pyomo/repn/tests/ampl/small6.pyomo.nl
  pyomo/repn/tests/ampl/small7.pyomo.nl
  pyomo/repn/tests/baron/small10.pyomo.bar
  pyomo/repn/tests/baron/small11.pyomo.bar
  pyomo/repn/tests/baron/small12.pyomo.bar
  pyomo/repn/tests/baron/small13.pyomo.bar
  pyomo/repn/tests/baron/small5.pyomo.bar
  pyomo/repn/tests/baron/small6.pyomo.bar
  pyomo/repn/tests/baron/small7.pyomo.bar
  pyomo/repn/tests/baron/small8.pyomo.bar
  pyomo/repn/tests/baron/small9.pyomo.bar
  pyomo/repn/tests/gams/no_column_ordering_linear.gams.baseline
  pyomo/repn/tests/gams/no_column_ordering_quadratic.gams.baseline
  pyomo/repn/tests/gams/no_row_ordering.gams.baseline
  pyomo/repn/tests/gams/small1.pyomo.gms
  pyomo/repn/tests/gams/small10.pyomo.gms
  pyomo/repn/tests/gams/small11.pyomo.gms
  pyomo/repn/tests/gams/small12.pyomo.gms
  pyomo/repn/tests/gams/small13.pyomo.gms
  pyomo/repn/tests/gams/small14a.pyomo.gms
  pyomo/repn/tests/gams/small15.pyomo.gms
  pyomo/repn/tests/gams/small2.pyomo.gms
  pyomo/repn/tests/gams/small3.pyomo.gms
  pyomo/repn/tests/gams/small4.pyomo.gms
  pyomo/repn/tests/gams/small5.pyomo.gms
  pyomo/repn/tests/gams/small6.pyomo.gms
  pyomo/repn/tests/gams/small7.pyomo.gms
  pyomo/repn/tests/gams/small8.pyomo.gms
  pyomo/repn/tests/gams/small9.pyomo.gms
  pyomo/repn/tests/gams/test_gams.py
  pyomo/repn/tests/gams/var_on_deactivated_block.gams.baseline
  pyomo/repn/tests/test_standard.py
Labels: PEP

#1085 MPEC descend into disjuncts
  pyomo/mpec/plugins/mpec1.py
  pyomo/mpec/plugins/mpec2.py
  pyomo/mpec/plugins/mpec3.py
  pyomo/mpec/plugins/mpec4.py
  pyomo/mpec/tests/test_complementarity.py
Labels: AT: STALE
