Repository Pyomo/pyomo, pull requests merged in 2019-02, with the labels that each got.

#848 Implementing basic step example
  examples/gdp/small_lit/basic_step.py
  pyomo/gdp/basic_step.py
  pyomo/gdp/plugins/gdp_var_mover.py
Labels: IDAES related

#857 Narrowing the check for a valid baron license.
  pyomo/solvers/plugins/solvers/BARON.py
Labels: pyomo.solvers, testing_and_ci

#847 GDP Branch and Bound Solver
  doc/OnlineDocs/contributed_packages/gdpbb.rst
  pyomo/contrib/gdpbb/GDPbb.py
  pyomo/contrib/gdpbb/__init__.py
  pyomo/contrib/gdpbb/plugins.py
  pyomo/contrib/gdpbb/test_GDPbb.py
  pyomo/environ/__init__.py
  pyomo/gdp/plugins/fix_disjuncts.py
Labels: IDAES related

#880 Update Travis Configuration
  .coveragerc
  .travis.yml
Labels: testing_and_ci

#872 calculate_variable_from_constraint: catching expression evaluation errors
  pyomo/core/expr/expr_pyomo5.py
  pyomo/util/calc_var_value.py
  pyomo/util/tests/test_calc_var_value.py
Labels: IDAES related

#862 Satisfiability Solver using z3
  doc/OnlineDocs/contributed_packages/satsolver.rst
  pyomo/contrib/satsolver/__init__.py
  pyomo/contrib/satsolver/satsolver.py
  pyomo/contrib/satsolver/test_satsolver.py
Labels: IDAES related

#887 Activate coverage for Anaconda Travis Builds
  .travis.yml
Labels: testing_and_ci
